// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package phonebook

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListContactsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListContactsRequest) Reset()         { *m = ListContactsRequest{} }
func (m *ListContactsRequest) String() string { return proto.CompactTextString(m) }
func (*ListContactsRequest) ProtoMessage()    {}
func (*ListContactsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *ListContactsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContactsRequest.Unmarshal(m, b)
}
func (m *ListContactsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContactsRequest.Marshal(b, m, deterministic)
}
func (m *ListContactsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContactsRequest.Merge(m, src)
}
func (m *ListContactsRequest) XXX_Size() int {
	return xxx_messageInfo_ListContactsRequest.Size(m)
}
func (m *ListContactsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContactsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListContactsRequest proto.InternalMessageInfo

type ListContactsResponse struct {
	Contacts             []*ListContactsResponse_SingleContact `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ListContactsResponse) Reset()         { *m = ListContactsResponse{} }
func (m *ListContactsResponse) String() string { return proto.CompactTextString(m) }
func (*ListContactsResponse) ProtoMessage()    {}
func (*ListContactsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ListContactsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContactsResponse.Unmarshal(m, b)
}
func (m *ListContactsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContactsResponse.Marshal(b, m, deterministic)
}
func (m *ListContactsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContactsResponse.Merge(m, src)
}
func (m *ListContactsResponse) XXX_Size() int {
	return xxx_messageInfo_ListContactsResponse.Size(m)
}
func (m *ListContactsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContactsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListContactsResponse proto.InternalMessageInfo

func (m *ListContactsResponse) GetContacts() []*ListContactsResponse_SingleContact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type ListContactsResponse_SingleContact struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListContactsResponse_SingleContact) Reset()         { *m = ListContactsResponse_SingleContact{} }
func (m *ListContactsResponse_SingleContact) String() string { return proto.CompactTextString(m) }
func (*ListContactsResponse_SingleContact) ProtoMessage()    {}
func (*ListContactsResponse_SingleContact) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1, 0}
}

func (m *ListContactsResponse_SingleContact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContactsResponse_SingleContact.Unmarshal(m, b)
}
func (m *ListContactsResponse_SingleContact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContactsResponse_SingleContact.Marshal(b, m, deterministic)
}
func (m *ListContactsResponse_SingleContact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContactsResponse_SingleContact.Merge(m, src)
}
func (m *ListContactsResponse_SingleContact) XXX_Size() int {
	return xxx_messageInfo_ListContactsResponse_SingleContact.Size(m)
}
func (m *ListContactsResponse_SingleContact) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContactsResponse_SingleContact.DiscardUnknown(m)
}

var xxx_messageInfo_ListContactsResponse_SingleContact proto.InternalMessageInfo

func (m *ListContactsResponse_SingleContact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListContactsResponse_SingleContact) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type GetContactRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactRequest) Reset()         { *m = GetContactRequest{} }
func (m *GetContactRequest) String() string { return proto.CompactTextString(m) }
func (*GetContactRequest) ProtoMessage()    {}
func (*GetContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *GetContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactRequest.Unmarshal(m, b)
}
func (m *GetContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactRequest.Marshal(b, m, deterministic)
}
func (m *GetContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactRequest.Merge(m, src)
}
func (m *GetContactRequest) XXX_Size() int {
	return xxx_messageInfo_GetContactRequest.Size(m)
}
func (m *GetContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactRequest proto.InternalMessageInfo

func (m *GetContactRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetContactResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactResponse) Reset()         { *m = GetContactResponse{} }
func (m *GetContactResponse) String() string { return proto.CompactTextString(m) }
func (*GetContactResponse) ProtoMessage()    {}
func (*GetContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GetContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactResponse.Unmarshal(m, b)
}
func (m *GetContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactResponse.Marshal(b, m, deterministic)
}
func (m *GetContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactResponse.Merge(m, src)
}
func (m *GetContactResponse) XXX_Size() int {
	return xxx_messageInfo_GetContactResponse.Size(m)
}
func (m *GetContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactResponse proto.InternalMessageInfo

func (m *GetContactResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetContactResponse) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type AddContactRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContactRequest) Reset()         { *m = AddContactRequest{} }
func (m *AddContactRequest) String() string { return proto.CompactTextString(m) }
func (*AddContactRequest) ProtoMessage()    {}
func (*AddContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *AddContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactRequest.Unmarshal(m, b)
}
func (m *AddContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactRequest.Marshal(b, m, deterministic)
}
func (m *AddContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactRequest.Merge(m, src)
}
func (m *AddContactRequest) XXX_Size() int {
	return xxx_messageInfo_AddContactRequest.Size(m)
}
func (m *AddContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactRequest proto.InternalMessageInfo

func (m *AddContactRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddContactRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type AddContactResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContactResponse) Reset()         { *m = AddContactResponse{} }
func (m *AddContactResponse) String() string { return proto.CompactTextString(m) }
func (*AddContactResponse) ProtoMessage()    {}
func (*AddContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *AddContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactResponse.Unmarshal(m, b)
}
func (m *AddContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactResponse.Marshal(b, m, deterministic)
}
func (m *AddContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactResponse.Merge(m, src)
}
func (m *AddContactResponse) XXX_Size() int {
	return xxx_messageInfo_AddContactResponse.Size(m)
}
func (m *AddContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactResponse proto.InternalMessageInfo

func (m *AddContactResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddContactResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddContactResponse) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type AddContactsResponse struct {
	Ids                  []int32  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContactsResponse) Reset()         { *m = AddContactsResponse{} }
func (m *AddContactsResponse) String() string { return proto.CompactTextString(m) }
func (*AddContactsResponse) ProtoMessage()    {}
func (*AddContactsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *AddContactsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactsResponse.Unmarshal(m, b)
}
func (m *AddContactsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactsResponse.Marshal(b, m, deterministic)
}
func (m *AddContactsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactsResponse.Merge(m, src)
}
func (m *AddContactsResponse) XXX_Size() int {
	return xxx_messageInfo_AddContactsResponse.Size(m)
}
func (m *AddContactsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactsResponse proto.InternalMessageInfo

func (m *AddContactsResponse) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type DeleteContactRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteContactRequest) Reset()         { *m = DeleteContactRequest{} }
func (m *DeleteContactRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteContactRequest) ProtoMessage()    {}
func (*DeleteContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *DeleteContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContactRequest.Unmarshal(m, b)
}
func (m *DeleteContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContactRequest.Marshal(b, m, deterministic)
}
func (m *DeleteContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContactRequest.Merge(m, src)
}
func (m *DeleteContactRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteContactRequest.Size(m)
}
func (m *DeleteContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContactRequest proto.InternalMessageInfo

func (m *DeleteContactRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteContactResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteContactResponse) Reset()         { *m = DeleteContactResponse{} }
func (m *DeleteContactResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteContactResponse) ProtoMessage()    {}
func (*DeleteContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *DeleteContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContactResponse.Unmarshal(m, b)
}
func (m *DeleteContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContactResponse.Marshal(b, m, deterministic)
}
func (m *DeleteContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContactResponse.Merge(m, src)
}
func (m *DeleteContactResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteContactResponse.Size(m)
}
func (m *DeleteContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContactResponse proto.InternalMessageInfo

func (m *DeleteContactResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*ListContactsRequest)(nil), "phonebook.ListContactsRequest")
	proto.RegisterType((*ListContactsResponse)(nil), "phonebook.ListContactsResponse")
	proto.RegisterType((*ListContactsResponse_SingleContact)(nil), "phonebook.ListContactsResponse.SingleContact")
	proto.RegisterType((*GetContactRequest)(nil), "phonebook.GetContactRequest")
	proto.RegisterType((*GetContactResponse)(nil), "phonebook.GetContactResponse")
	proto.RegisterType((*AddContactRequest)(nil), "phonebook.AddContactRequest")
	proto.RegisterType((*AddContactResponse)(nil), "phonebook.AddContactResponse")
	proto.RegisterType((*AddContactsResponse)(nil), "phonebook.AddContactsResponse")
	proto.RegisterType((*DeleteContactRequest)(nil), "phonebook.DeleteContactRequest")
	proto.RegisterType((*DeleteContactResponse)(nil), "phonebook.DeleteContactResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0xc7, 0x69, 0x2b, 0x46, 0x06, 0x21, 0x32, 0x40, 0x42, 0x1a, 0xc5, 0x66, 0x4d, 0x84, 0x8b,
	0x3d, 0xe0, 0x13, 0xa8, 0x18, 0x83, 0x1a, 0x8d, 0xd5, 0x93, 0x37, 0xa0, 0x13, 0x6d, 0x84, 0x2e,
	0xd2, 0xc5, 0xc4, 0xe7, 0xf1, 0xe2, 0x63, 0x1a, 0xd7, 0xda, 0x6e, 0x69, 0x9b, 0x26, 0xdc, 0x36,
	0xf3, 0xf1, 0x9b, 0x8f, 0xff, 0x64, 0xa1, 0x16, 0xd0, 0xf2, 0xc3, 0x9b, 0x92, 0xbd, 0x58, 0x72,
	0xc1, 0xb1, 0xb2, 0x78, 0xe5, 0x3e, 0x4d, 0x38, 0x7f, 0x63, 0x6d, 0x68, 0xde, 0x7a, 0x81, 0xb8,
	0xe0, 0xbe, 0x18, 0x4f, 0x45, 0xe0, 0xd0, 0xfb, 0x8a, 0x02, 0xc1, 0xbe, 0x35, 0x68, 0x25, 0xed,
	0xc1, 0x82, 0xfb, 0x01, 0xe1, 0x08, 0x76, 0xa6, 0xa1, 0xad, 0xa3, 0x59, 0x46, 0xbf, 0x3a, 0x38,
	0xb1, 0x23, 0x9a, 0x9d, 0x95, 0x62, 0x3f, 0x7a, 0xfe, 0xcb, 0x8c, 0x42, 0xb3, 0x13, 0xa5, 0x9b,
	0x97, 0x50, 0x4b, 0xb8, 0x10, 0x61, 0xcb, 0x1f, 0xcf, 0xa9, 0xa3, 0x59, 0x5a, 0xbf, 0xe2, 0xc8,
	0x37, 0x5a, 0x50, 0x95, 0xf8, 0xbb, 0xd5, 0x7c, 0x42, 0xcb, 0x8e, 0x2e, 0x5d, 0xaa, 0x89, 0x1d,
	0x41, 0xe3, 0x8a, 0xfe, 0xab, 0x86, 0xfd, 0x63, 0x1d, 0x74, 0xcf, 0x95, 0xa0, 0xb2, 0xa3, 0x7b,
	0x2e, 0xbb, 0x06, 0x54, 0x83, 0xc2, 0x61, 0x36, 0x2b, 0x38, 0x82, 0xc6, 0x99, 0xeb, 0xae, 0x15,
	0xdc, 0x0c, 0xf5, 0x0c, 0xa8, 0xa2, 0xc2, 0xb6, 0xd6, 0x9a, 0x8f, 0xd8, 0x7a, 0x3e, 0xdb, 0x48,
	0xb3, 0x7b, 0xd0, 0x8c, 0xd9, 0xb1, 0x80, 0x7b, 0x60, 0x78, 0xee, 0x9f, 0x76, 0x65, 0xe7, 0xf7,
	0xc9, 0x8e, 0xa1, 0x35, 0xa4, 0x19, 0x09, 0x2a, 0xd8, 0x61, 0x0f, 0xda, 0x6b, 0x71, 0xd9, 0xfd,
	0x0e, 0xbe, 0x0c, 0x88, 0x2f, 0x0c, 0x1f, 0x60, 0x57, 0x3d, 0x0b, 0xec, 0xe6, 0xde, 0x8b, 0x2c,
	0x6b, 0x1e, 0x16, 0xdc, 0x13, 0x2b, 0xe1, 0x3d, 0xd4, 0x63, 0x35, 0xcf, 0x3f, 0x47, 0x43, 0xdc,
	0x57, 0x92, 0x52, 0xd7, 0x60, 0x1e, 0xe4, 0x78, 0x23, 0xe0, 0x0d, 0x40, 0xbc, 0xab, 0x04, 0x2c,
	0xa5, 0x74, 0x02, 0x96, 0x16, 0x8f, 0x95, 0xf0, 0x09, 0x6a, 0x89, 0x3d, 0xa1, 0x3a, 0x51, 0xd6,
	0xa6, 0x4d, 0x2b, 0x3f, 0x40, 0x99, 0xb9, 0xaa, 0xc8, 0x59, 0xd0, 0x63, 0x37, 0xd3, 0xab, 0xac,
	0xb0, 0xaf, 0x4d, 0xb6, 0xe5, 0x5f, 0x70, 0xfa, 0x13, 0x00, 0x00, 0xff, 0xff, 0x93, 0x7e, 0x52,
	0x2a, 0x1c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PhonebookClient is the client API for Phonebook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PhonebookClient interface {
	ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error)
	GetContactByID(ctx context.Context, in *GetContactRequest, opts ...grpc.CallOption) (*GetContactResponse, error)
	AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*AddContactResponse, error)
	DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*DeleteContactResponse, error)
	AddContacts(ctx context.Context, opts ...grpc.CallOption) (Phonebook_AddContactsClient, error)
}

type phonebookClient struct {
	cc *grpc.ClientConn
}

func NewPhonebookClient(cc *grpc.ClientConn) PhonebookClient {
	return &phonebookClient{cc}
}

func (c *phonebookClient) ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error) {
	out := new(ListContactsResponse)
	err := c.cc.Invoke(ctx, "/phonebook.phonebook/ListContacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phonebookClient) GetContactByID(ctx context.Context, in *GetContactRequest, opts ...grpc.CallOption) (*GetContactResponse, error) {
	out := new(GetContactResponse)
	err := c.cc.Invoke(ctx, "/phonebook.phonebook/GetContactByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phonebookClient) AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*AddContactResponse, error) {
	out := new(AddContactResponse)
	err := c.cc.Invoke(ctx, "/phonebook.phonebook/AddContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phonebookClient) DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*DeleteContactResponse, error) {
	out := new(DeleteContactResponse)
	err := c.cc.Invoke(ctx, "/phonebook.phonebook/DeleteContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phonebookClient) AddContacts(ctx context.Context, opts ...grpc.CallOption) (Phonebook_AddContactsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Phonebook_serviceDesc.Streams[0], "/phonebook.phonebook/AddContacts", opts...)
	if err != nil {
		return nil, err
	}
	x := &phonebookAddContactsClient{stream}
	return x, nil
}

type Phonebook_AddContactsClient interface {
	Send(*AddContactRequest) error
	CloseAndRecv() (*AddContactsResponse, error)
	grpc.ClientStream
}

type phonebookAddContactsClient struct {
	grpc.ClientStream
}

func (x *phonebookAddContactsClient) Send(m *AddContactRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *phonebookAddContactsClient) CloseAndRecv() (*AddContactsResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AddContactsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PhonebookServer is the server API for Phonebook service.
type PhonebookServer interface {
	ListContacts(context.Context, *ListContactsRequest) (*ListContactsResponse, error)
	GetContactByID(context.Context, *GetContactRequest) (*GetContactResponse, error)
	AddContact(context.Context, *AddContactRequest) (*AddContactResponse, error)
	DeleteContact(context.Context, *DeleteContactRequest) (*DeleteContactResponse, error)
	AddContacts(Phonebook_AddContactsServer) error
}

func RegisterPhonebookServer(s *grpc.Server, srv PhonebookServer) {
	s.RegisterService(&_Phonebook_serviceDesc, srv)
}

func _Phonebook_ListContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServer).ListContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonebook.phonebook/ListContacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServer).ListContacts(ctx, req.(*ListContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Phonebook_GetContactByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServer).GetContactByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonebook.phonebook/GetContactByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServer).GetContactByID(ctx, req.(*GetContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Phonebook_AddContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServer).AddContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonebook.phonebook/AddContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServer).AddContact(ctx, req.(*AddContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Phonebook_DeleteContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServer).DeleteContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonebook.phonebook/DeleteContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServer).DeleteContact(ctx, req.(*DeleteContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Phonebook_AddContacts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PhonebookServer).AddContacts(&phonebookAddContactsServer{stream})
}

type Phonebook_AddContactsServer interface {
	SendAndClose(*AddContactsResponse) error
	Recv() (*AddContactRequest, error)
	grpc.ServerStream
}

type phonebookAddContactsServer struct {
	grpc.ServerStream
}

func (x *phonebookAddContactsServer) SendAndClose(m *AddContactsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *phonebookAddContactsServer) Recv() (*AddContactRequest, error) {
	m := new(AddContactRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Phonebook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phonebook.phonebook",
	HandlerType: (*PhonebookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListContacts",
			Handler:    _Phonebook_ListContacts_Handler,
		},
		{
			MethodName: "GetContactByID",
			Handler:    _Phonebook_GetContactByID_Handler,
		},
		{
			MethodName: "AddContact",
			Handler:    _Phonebook_AddContact_Handler,
		},
		{
			MethodName: "DeleteContact",
			Handler:    _Phonebook_DeleteContact_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddContacts",
			Handler:       _Phonebook_AddContacts_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
